### ISSUE TITLE
Remove TD Ameritrade branding on Context example

### ISSUE THREAD

**Issue by DSchau** [objectpartners/react-redux-workshop#62]
[This slide](https://react-training.objectpartners.com/slidedeck/#/9/6)

If you need to fork the sandbox, please do!

**Comment by hartstinger** [comment]
Are these changes along the lines that you're thinking? I kept the footer for demonstration purposes.

https://codesandbox.io/s/w2y6jknwjw

**Comment by DSchau** [comment]
That is perfect!
