### ISSUE TITLE
_Consider_ changing all code snippet answers in the labs to use details/summary

### ISSUE THREAD

**Issue by DSchau** [objectpartners/react-redux-workshop#65]
You can details/summary to display content as collapsible. This will slightly lessen the copy/pasting that people tend to do. An example

````
<details>
<summary>Click to expand me pls</summary>
```js
var a = 'b';
```
</details>
````

<details>
<summary>Click to expand me pls</summary>
```js
var a = 'b';
```
</details>

**Comment by DSchau** [comment]
Note: I am not 100% sure this will work with `gatsby-transformer-remark` but it's worth a shot!

**Comment by hartstinger** [comment]
First trial at this showed `<details>` support is big 🚫 
Preliminary searching shows we're not the only ones wanting this behavior, but I don't have enough information to know how/if we can get around this .. yet.

**Comment by DSchau** [comment]
... woo hoo?! 🎉  Were you confused by the syntax, because I sure was haha

**Comment by hartstinger** [comment]
No, I'm thoroughly confused by this one. Because I found an example where we're already using the `<details>` but it does *not* like it right after a bullet point. So .. while i was wrong originally, I'm still not .. right 😕

**Comment by DSchau** [comment]
Dumb question, but did you try increasing the spacing? Sometimes two line breaks are required for things to "reset."

**Comment by hartstinger** [comment]
Ok so not a dumb question. Clearly i had only done _one_ blank space instead of _two_. And two is the magic number. 😩
